apiVersion: apps/v1
kind: Deployment
metadata:
  name: banking-app
  namespace: banking
spec:
  replicas: 2
  selector:
    matchLabels:
      app: banking-app
  template:
    metadata:
      labels:
        app: banking-app
    spec:
      containers:
        - name: banking-app
          image: harbor.local/banking/banking-app:latest
          ports:
            - containerPort: 8080

          # 🚀 Production readiness
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "500m"

          # Health checks (VERY IMPORTANT for EX280)
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 40
            periodSeconds: 20
